/*
  Automatically generated by Autodist 1.3.  Do not edit.

  Generated: Tue May 10 17:22:35 EEST 2005 by priikone
  Distribution: Toolkit
  License: distdir/TOOLKIT
*/

#ifndef _SILC_DISTDEFS_H
#define _SILC_DISTDEFS_H

#define SILC_DIST_APPS 1
#define SILC_DIST_CLIENT 1
#define SILC_DIST_CLIENTLIB 1
#define SILC_DIST_COMPILER 1
#define SILC_DIST_DOC 1
#define SILC_DIST_INCLUDES 1
#define SILC_DIST_LIB 1
#define SILC_DIST_MATH 1
#define SILC_DIST_SERVER 1
#define SILC_DIST_SFTP 1
#define SILC_DIST_SILC 1
#define SILC_DIST_SIM 1
#define SILC_DIST_TMA 1
#define SILC_DIST_TOOLKIT 1

#endif /* _SILC_DISTDEFS_H */
