/* Automatically generated by ./prepare */
#define SILC_VERSION_STRING "0.9.12"
#define SILC_DIST_VERSION_STRING "0.9.12"
#define SILC_PROTOCOL_VERSION_STRING "SILC-1.2-0.9.12 toolkit"
#define SILC_NAME "SILC toolkit"
